#!/bin/sh
# numberpyramid
# This program creates a sideways numerical pyramid with the number of columns
# determined by user input. 
# Jameel Kaba / jkaba / 250796017

# Ask the user for the number of columns
echo "Type the number of columns the pyramid should have"

# Read the input and assign it a value numcol
read numcol

# If the value of numcol is greater than 0
if [ $numcol -gt 0 ]

# Then assign i the value of 0
then i=0

# While the value of i is less than numcol-1
while [ $i -lt $numcol-1 ]

# Set j equal to zero
do j=0

# While the value of j is less than the value of i-1
while [ $j -lt $i-1 ]

# Print the value of j before increasing the value of j by 1
do printf  " $j"; j=`expr $j + 1`

# Exit the second while loop and print a new line
done
printf "\n" 

# Increase the value of i by 1 before exiting the first while loop
i=`expr $i + 1`
done

# Set i equal to the value of numcol
i="$numcol"

# While i is greater than or equal to 0
while [ $i -ge 0 ]

# Set j equal to 0
do j=0

# While j is less than i-1
while [ $j -lt $i-1 ]

# Print the value of j and increment it by 1 before exiting the loop
do printf " $j"; j=`expr $j + 1`;
done

# Print a new line before decreasing i by 1 and exiting the loop
printf "\n"; i=`expr $i - 1`;
done

# If the value of n is 0 then do nothing
else :
fi
