city(chicago).
city(newyork).
city(losangeles).
city(boston).
city(toronto).
city(vancouver).
city(dallas).
city(miami).
city(phoenix).
city(seattle).
city(cleveland).
city(buffalo).

airport(ohare).
airport(midway).
airport(jfk).
airport(liberty).
airport(california).
airport(logan).
airport(pearson).
airport(city).
airport(vanc).
airport(seatac).
airport(southern).
airport(northern).

has_airport(chicago,ohare).
has_airport(chicago,midway).
has_airport(newyork,jfk).
has_airport(losangeles,liberty).
has_airport(losangeles,california).
has_airport(boston,logan).
has_airport(toronto,pearson).
has_airport(toronto,city).
has_airport(vancouver,vanc).
has_airport(seattle,seatac).
has_airport(dallas,southern).
has_airport(miami,southern).
has_airport(phoenix,city).
has_airport(cleveland,northern).
has_airport(buffalo,northern).

ww2hero(ohare).
ww2hero(jfk).
ww2hero(pearson).
ww2hero(logan).

ww2battle(midway).
ww2battle(southern).
ww2battle(northern).
ww2battle(california).