#!/bin/sh
# odd_prn
# this program echoes the shell script file name as well as the value of its
# odd arguments. If no argument is provided then only the shell script file
# name is returned.
# Jameel Kaba / jkaba / 250796017
# echo/print the shell script file name
echo "$0"

# loop through all arguments assigning them to a variable i
for i in $*

# for each loop echo/print the first argument
do echo "$1"

# if the second argument is not an empty string
if [ ! -z "$2" ]

# then shift two arguments down, this deletes whatever arguments that were
# in position one and two
then shift 2

# else if the second argument is empty then exit
else exit

# finish/exit the if statement and the loop
fi
done



